package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/gilsstudio/mhelm/internal/chartfile"
	"github.com/gilsstudio/mhelm/internal/discover"
	"github.com/gilsstudio/mhelm/internal/lockfile"
	"github.com/spf13/cobra"
	"sigs.k8s.io/yaml"
)

var discoverCheck bool

const imageValuesHeader = "# Auto-generated by mhelm discover. Pass to `helm install --values` after mirroring.\n"

var discoverCmd = &cobra.Command{
	Use:   "discover [dir]",
	Short: "Render the chart and discover every container image it references",
	Long: `Read <dir>/chart.json, pull the upstream chart (read-only), render it
with the values listed in chart.json's valuesFiles, walk the rendered K8s
manifests for container image refs, and write the discovered images into
<dir>/chart-lock.json.

If <dir>/chart-lock.json already exists (e.g. produced by a prior 'mhelm mirror'
run), the chart + upstream + downstream + mirror sections are preserved and only
the images section is updated.

Network reads only — no pushes, no signing.

With --check the artifacts are computed but NOT written: mhelm compares
what discover would produce against the committed chart-lock.json /
image-values.yaml and exits 2 if they differ (0 = in sync, 1 = operational
error). Use it as a PR gate to require discover to have been re-run after a
chart.json edit. The discover-metadata stamp (tool/version/timestamp) is
ignored by the comparison — only the discovered content matters.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		dir := "."
		if len(args) == 1 {
			dir = args[0]
		}
		chartPath := filepath.Join(dir, chartFileName)
		lockPath := filepath.Join(dir, lockFileName)

		cf, err := chartfile.Load(chartPath)
		if err != nil {
			return fmt.Errorf("load %s: %w", chartPath, err)
		}
		if err := cf.Validate(); err != nil {
			return err
		}

		res, err := discover.Run(cmd.Context(), cf, dir)
		if err != nil {
			return err
		}

		prior, readErr := lockfile.Read(lockPath)
		if readErr != nil && !errors.Is(readErr, os.ErrNotExist) {
			return fmt.Errorf("read %s: %w", lockPath, readErr)
		}
		priorExists := readErr == nil
		imageValuesPath := filepath.Join(dir, imageValuesFileName)

		candidate, lockBytes, imgVals, imgSkip, err := buildArtifacts(res, prior, cf)
		if err != nil {
			return err
		}

		// Discovery summary — printed in both modes.
		fmt.Fprintf(cmd.OutOrStdout(), "discovered %s:%s — %d image(s)\n", res.ChartName, res.ChartVersion, len(res.Images))
		for _, img := range res.Images {
			suffix := " (digest unresolved)"
			if img.Digest != "" {
				suffix = " @ " + img.Digest
			}
			fmt.Fprintf(cmd.OutOrStdout(), "  [%s] %s%s\n", img.Source, img.Ref, suffix)
			for _, vp := range img.ValuesPaths {
				fmt.Fprintf(cmd.OutOrStdout(), "    ← values path: %s (%s)\n", vp.Path, vp.Accuracy)
			}
		}

		if discoverCheck {
			return runCheck(cmd, imageValuesPath, prior, priorExists, candidate, imgVals, imgSkip)
		}

		if err := os.WriteFile(lockPath, lockBytes, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", lockPath, err)
		}
		fmt.Fprintf(cmd.OutOrStdout(), "lockfile:      %s\n", lockPath)
		if imgVals != nil {
			if err := os.WriteFile(imageValuesPath, imgVals, 0o644); err != nil {
				return fmt.Errorf("write %s: %w", imageValuesPath, err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "image values:  %s\n", imageValuesPath)
		} else {
			fmt.Fprintf(cmd.OutOrStdout(), "image values:  none (%s)\n", imgSkip)
		}
		return nil
	},
}

// buildArtifacts assembles the would-be lockfile + image-values bytes from
// a discover.Result and the prior on-disk lockfile, WITHOUT writing.
// Shared by normal and --check modes so the two cannot diverge.
func buildArtifacts(res discover.Result, prior lockfile.File, cf chartfile.File) (lockfile.File, []byte, []byte, string, error) {
	lf := prior
	lf.APIVersion = lockfile.APIVersion
	lf.Mirror.Chart = lockfile.Chart{Name: res.ChartName, Version: res.ChartVersion}
	lf.Mirror.Upstream.Type = cf.Mirror.Upstream.Type
	lf.Mirror.Upstream.URL = cf.Mirror.Upstream.URL
	lf.Mirror.Upstream.ChartContentDigest = res.ChartContentDigest
	if res.UpstreamManifestDigest != "" {
		lf.Mirror.Upstream.OCIManifestDigest = res.UpstreamManifestDigest
	}
	lf.Mirror.Images = res.Images
	// Stamp discover metadata when no prior mirror run has — keeps the
	// lockfile self-describing about who produced the image list. The
	// stamp is normalized away by --check (see normForCompare).
	if lf.Mirror.Tool == "" {
		lf.Mirror.Tool = "mhelm discover"
		lf.Mirror.Version = Version
		lf.Mirror.Timestamp = time.Now().UTC()
	}
	lockBytes, err := lockfile.Marshal(lf)
	if err != nil {
		return lf, nil, nil, "", err
	}

	switch {
	case cf.Wrap != nil:
		return lf, lockBytes, nil, "chart.json has a wrap section — wrapper's values.yaml carries the rewrites", nil
	case len(res.MirrorValues) == 0:
		return lf, lockBytes, nil, "no values paths matched discovered images", nil
	default:
		b, err := yaml.Marshal(res.MirrorValues)
		if err != nil {
			return lf, lockBytes, nil, "", fmt.Errorf("marshal image values: %w", err)
		}
		return lf, lockBytes, append([]byte(imageValuesHeader), b...), "", nil
	}
}

// normForCompare zeroes the producer stamp so --check compares discovered
// content, not "when discovered".
func normForCompare(f lockfile.File) lockfile.File {
	f.Mirror.Tool, f.Mirror.Version, f.Mirror.Timestamp = "", "", time.Time{}
	if f.Wrap != nil {
		w := *f.Wrap
		w.Tool, w.Version, w.Timestamp = "", "", time.Time{}
		f.Wrap = &w
	}
	return f
}

// runCheck compares the would-be artifacts against what's committed and
// exits 2 if they differ (0 = in sync, 1 = operational error).
func runCheck(cmd *cobra.Command, imageValuesPath string, prior lockfile.File, priorExists bool, candidate lockfile.File, imgVals []byte, imgSkip string) error {
	out := cmd.OutOrStdout()
	stale := false

	candN, err := lockfile.Marshal(normForCompare(candidate))
	if err != nil {
		return err
	}
	switch {
	case !priorExists:
		fmt.Fprintln(out, "chart-lock.json: would create")
		stale = true
	default:
		priorN, err := lockfile.Marshal(normForCompare(prior))
		if err != nil {
			return err
		}
		if bytes.Equal(candN, priorN) {
			fmt.Fprintln(out, "chart-lock.json: OK")
		} else {
			fmt.Fprintln(out, "chart-lock.json: would change")
			for _, l := range imageDelta(prior.Mirror.Images, candidate.Mirror.Images) {
				fmt.Fprintf(out, "  %s\n", l)
			}
			stale = true
		}
	}

	if imgVals == nil {
		// Intentionally skipped (e.g. wrap charts) — never a failing diff.
		if _, statErr := os.Stat(imageValuesPath); statErr == nil {
			fmt.Fprintf(out, "%s: skip — stale file on disk (%s)\n", imageValuesFileName, imgSkip)
		} else {
			fmt.Fprintf(out, "%s: skip (%s)\n", imageValuesFileName, imgSkip)
		}
	} else {
		onDisk, readErr := os.ReadFile(imageValuesPath)
		switch {
		case errors.Is(readErr, os.ErrNotExist):
			fmt.Fprintf(out, "%s: would create\n", imageValuesFileName)
			stale = true
		case readErr != nil:
			return fmt.Errorf("read %s: %w", imageValuesPath, readErr)
		case bytes.Equal(onDisk, imgVals):
			fmt.Fprintf(out, "%s: OK\n", imageValuesFileName)
		default:
			fmt.Fprintf(out, "%s: would change\n", imageValuesFileName)
			stale = true
		}
	}

	if stale {
		fmt.Fprintln(out, "stale — re-run `mhelm discover` and commit the result")
		os.Exit(2)
	}
	fmt.Fprintln(out, "in sync")
	return nil
}

// imageDelta is a compact ref→digest diff for the --check summary.
func imageDelta(prior, cand []lockfile.Image) []string {
	pm := make(map[string]string, len(prior))
	for _, i := range prior {
		pm[i.Ref] = i.Digest
	}
	cm := make(map[string]string, len(cand))
	for _, i := range cand {
		cm[i.Ref] = i.Digest
	}
	var lines []string
	for _, i := range cand {
		if d, ok := pm[i.Ref]; !ok {
			lines = append(lines, "+ "+i.Ref)
		} else if d != i.Digest {
			lines = append(lines, "~ "+i.Ref+" digest "+d+" → "+i.Digest)
		}
	}
	for _, i := range prior {
		if _, ok := cm[i.Ref]; !ok {
			lines = append(lines, "- "+i.Ref)
		}
	}
	return lines
}

func init() {
	discoverCmd.Flags().BoolVar(&discoverCheck, "check", false,
		"compute artifacts but don't write; exit 2 if chart-lock.json or image-values.yaml would change")
}
