package cmd

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/gilsstudio/mhelm/internal/chartfile"
	"github.com/gilsstudio/mhelm/internal/discover"
	"github.com/gilsstudio/mhelm/internal/lockfile"
	"github.com/spf13/cobra"
	"sigs.k8s.io/yaml"
)

var discoverCmd = &cobra.Command{
	Use:   "discover [dir]",
	Short: "Render the chart and discover every container image it references",
	Long: `Read <dir>/chart.json, pull the upstream chart (read-only), render it
with the values listed in chart.json's valuesFiles, walk the rendered K8s
manifests for container image refs, and write the discovered images into
<dir>/chart-lock.json.

If <dir>/chart-lock.json already exists (e.g. produced by a prior 'mhelm mirror'
run), the chart + upstream + downstream + mirror sections are preserved and only
the images section is updated.

Network reads only — no pushes, no signing.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		dir := "."
		if len(args) == 1 {
			dir = args[0]
		}
		chartPath := filepath.Join(dir, chartFileName)
		lockPath := filepath.Join(dir, lockFileName)

		cf, err := chartfile.Load(chartPath)
		if err != nil {
			return fmt.Errorf("load %s: %w", chartPath, err)
		}
		if err := cf.Validate(); err != nil {
			return err
		}

		res, err := discover.Run(cmd.Context(), cf, dir)
		if err != nil {
			return err
		}

		lf, err := lockfile.Read(lockPath)
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("read %s: %w", lockPath, err)
		}
		lf.SchemaVersion = lockfile.SchemaVersion
		lf.Chart = lockfile.Chart{Name: res.ChartName, Version: res.ChartVersion}
		lf.Upstream.Type = cf.Upstream.Type
		lf.Upstream.URL = cf.Upstream.URL
		lf.Upstream.ChartContentDigest = res.ChartContentDigest
		if res.UpstreamManifestDigest != "" {
			lf.Upstream.OCIManifestDigest = res.UpstreamManifestDigest
		}
		lf.Images = res.Images
		// Mirror section stays as-is if previously set; otherwise stamp discover metadata
		// so the lockfile is self-describing about who produced the image list.
		if lf.Mirror.Tool == "" {
			lf.Mirror = lockfile.Mirror{Tool: "mhelm discover", Version: Version, Timestamp: time.Now().UTC()}
		}

		if err := lockfile.Write(lockPath, lf); err != nil {
			return fmt.Errorf("write %s: %w", lockPath, err)
		}

		mirrorValuesPath := filepath.Join(dir, mirrorValuesFileName)
		wroteMirrorValues := false
		if len(res.MirrorValues) > 0 {
			b, err := yaml.Marshal(res.MirrorValues)
			if err != nil {
				return fmt.Errorf("marshal mirror values: %w", err)
			}
			header := "# Auto-generated by mhelm discover. Pass to `helm install --values` after mirroring.\n"
			if err := os.WriteFile(mirrorValuesPath, append([]byte(header), b...), 0o644); err != nil {
				return fmt.Errorf("write %s: %w", mirrorValuesPath, err)
			}
			wroteMirrorValues = true
		}

		fmt.Fprintf(cmd.OutOrStdout(), "discovered %s:%s — %d image(s)\n", res.ChartName, res.ChartVersion, len(res.Images))
		for _, img := range res.Images {
			suffix := ""
			if img.Digest != "" {
				suffix = " @ " + img.Digest
			} else {
				suffix = " (digest unresolved)"
			}
			fmt.Fprintf(cmd.OutOrStdout(), "  [%s] %s%s\n", img.Source, img.Ref, suffix)
			for _, vp := range img.ValuesPaths {
				fmt.Fprintf(cmd.OutOrStdout(), "    ← values path: %s (%s)\n", vp.Path, vp.Accuracy)
			}
		}
		fmt.Fprintf(cmd.OutOrStdout(), "lockfile:      %s\n", lockPath)
		if wroteMirrorValues {
			fmt.Fprintf(cmd.OutOrStdout(), "mirror values: %s\n", mirrorValuesPath)
		} else {
			fmt.Fprintln(cmd.OutOrStdout(), "mirror values: none (no values paths matched discovered images)")
		}
		return nil
	},
}
